### ISSUE TITLE
Installation failed when installing on new OS

### ISSUE THREAD

**Issue by its-arsalan** [kamilmahmood/fastzipfile#6]
I am getting this log message on my machine when I run the installation command.

Collecting fastzipfile
  Using cached https://files.pythonhosted.org/packages/98/0f/ca0ede2a91ce37835bde16ea3b9db9432d5c62d1cc06ca7a8e590a3f539c/fastzipfile-2.1.tar.gz
Building wheels for collected packages: fastzipfile
  Building wheel for fastzipfile (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/manager/ven3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ty3jmo5/fastzipfile/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ty3jmo5/fastzipfile/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-25bv6vcb --python-tag cp35
       cwd: /tmp/pip-install-0ty3jmo5/fastzipfile/
  Complete output (16 lines):
  /home/manager/ven3/lib/python3.5/site-packages/setuptools/dist.py:475: UserWarning: Normalizing 'v2.1' to '2.1'
    normalized_version,
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  copying fastzipfile.py -> build/lib.linux-x86_64-3.5
  running build_ext
  building '_zipdecrypter' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/extension
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/manager/ven3/include/python3.5m -c extension/_zipdecryptermodule.c -o build/temp.linux-x86_64-3.5/extension/_zipdecryptermodule.o -std=c99
  extension/_zipdecryptermodule.c:2:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fastzipfile
  Running setup.py clean for fastzipfile
Failed to build fastzipfile
Installing collected packages: fastzipfile
    Running setup.py install for fastzipfile ... error
    ERROR: Command errored out with exit status 1:
     command: /home/manager/ven3/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-0ty3jmo5/fastzipfile/setup.py'"'"'; __file__='"'"'/tmp/pip-install-0ty3jmo5/fastzipfile/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-79l1c3ta/install-record.txt --single-version-externally-managed --compile --install-headers /home/manager/ven3/include/site/python3.5/fastzipfile
         cwd: /tmp/pip-install-0ty3jmo5/fastzipfile/
    Complete output (16 lines):
    /home/manager/ven3/lib/python3.5/site-packages/setuptools/dist.py:475: UserWarning: Normalizing 'v2.1' to '2.1'
      normalized_version,
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    copying fastzipfile.py -> build/lib.linux-x86_64-3.5
    running build_ext
    building '_zipdecrypter' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -I/home/manager/ven3/include/python3.5m -c extension/_zipdecryptermodule.c -o build/temp.linux-x86_64-3.5/extension/_zipdecryptermodule.o -std=c99
    extension/_zipdecryptermodule.c:2:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by kamilmahmood** [comment]
`extension/_zipdecryptermodule.c:2:20: fatal error: Python.h: No such file or directory` is appearing because you have missing python development headers. For example on Ubuntu you can install Python 3 development headers using `sudo apt install python3-dev`
