### ISSUE TITLE
Could you update it to support python3.11 please.

### ISSUE THREAD

**Issue by chenzep** [kamilmahmood/fastzipfile#9]

**Comment by mxmlnkn** [comment]
I also want to vote for this issue. Would you review and merge a pull request?

**Comment by kamilmahmood** [comment]
Yes, please send

**Comment by kamilmahmood** [comment]
New version v2.3.1 is uploaded to PyPi from work of @mxmlnkn. v2.3 was yanked due to an issue that setuptools was unable to read its name while installing, then restored setup.py and source distribution is released instead of pre built wheels because of some error in github action wheels.yaml
